import { Theme } from '@mui/material/styles';

export const getSxClasses = (theme: Theme) => ({
  attributionContainer: {
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
    p: '15px',
    marginTop: '10px',
    width: '300px',
    padding: theme.spacing(0, 4),
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    alignItems: 'center',
    transition: 'opacity 1ms ease-in 300ms',
    '& .ol-attribution': {
      display: 'flex !important',
      flexDirection: 'row',
      position: 'relative',
      background: 'transparent !important',
      backgroundColor: 'transparent !important',
      borderRadius: 'initial',
      padding: 'initial',
      margin: 'initial',
      left: 'auto',
      top: 'auto',
      right: 'auto',
      bottom: 'auto',
      maxWidth: 'initial',
      textAlign: 'left',
      overflow: 'hidden',
      '& button:not(.expand-collapse-icon)': {
        display: 'none',
      },
      '& ul': {
        display: 'block',
        maxWidth: '500px',
        overflow: 'hidden',
        margin: 'initial',
        padding: 'initial',
        color: theme.palette.primary.light,
        textShadow: 'initial',
        fontSize: 'initial',
        '& li': {
          display: 'block',
          color: theme.palette.primary.light,
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          overflow: 'hidden',
        },
      },
    },
  },
});
