import { Icon as StyleIcon } from 'ol/style';
export declare const yellowIcon: StyleIcon;
export declare const yellow2xIcon: StyleIcon;
export declare const violetIcon: StyleIcon;
export declare const violet2xIcon: StyleIcon;
export declare const orangeIcon: StyleIcon;
export declare const orange2xIcon: StyleIcon;
export declare const greyIcon: StyleIcon;
export declare const grey2xIcon: StyleIcon;
export declare const goldIcon: StyleIcon;
export declare const gold2xIcon: StyleIcon;
export declare const blueIcon: StyleIcon;
export declare const blue2xIcon: StyleIcon;
export declare const blackIcon: StyleIcon;
export declare const black2xIcon: StyleIcon;
export declare const redIcon: StyleIcon;
export declare const red2xIcon: StyleIcon;
export declare const greenIcon: StyleIcon;
export declare const redGreenIcon: StyleIcon;
export declare const greenRedIcon: StyleIcon;
export declare const green2xIcon: StyleIcon;
export declare const blueCircleIcon: StyleIcon;
export declare const getClusterIconFull: (ratio: string) => string;
export declare const getClusterIconPart: (ratio: string) => string;
export declare const getClusterIconEmpty: (ratio: string) => string;
export declare const unselectedMarkerIconCreator: () => string;
export declare const selectedMarkerIconCreator: () => string;
