import { Map as OLMap, MapEvent } from 'ol';
import { Coordinate } from 'ol/coordinate';
import { ObjectEvent } from 'ol/Object';
import Overlay from 'ol/Overlay';
import { Extent } from 'ol/extent';
import { FitOptions } from 'ol/View';
import { TypeSetStore, TypeGetStore } from '@/core/stores/geoview-store';
import { TypeBasemapOptions, TypeMapFeaturesConfig, TypeValidMapProjectionCodes } from '@/core/types/global-types';
import { TypeFeatureInfoEntry, TypeMapMouseInfo } from '@/api/events/payloads';
import { TypeInteraction } from '@/geo/map/map-schema-types';
import { TypeClickMarker } from '@/app';
interface TypeScaleInfo {
    lineWidth: string;
    labelGraphic: string;
    labelNumeric: string;
}
export interface TypeNorthArrow {
    degreeRotation: string;
    isNorthVisible: boolean;
}
export interface IMapState {
    attribution: string[];
    basemapOptions: TypeBasemapOptions;
    centerCoordinates: Coordinate;
    clickCoordinates?: TypeMapMouseInfo;
    clickMarker: TypeClickMarker | undefined;
    currentProjection: TypeValidMapProjectionCodes;
    fixNorth: boolean;
    highlightedFeatures: Array<TypeFeatureInfoEntry>;
    interaction: TypeInteraction;
    pointerPosition?: TypeMapMouseInfo;
    mapElement?: OLMap;
    mapExtent: Extent | undefined;
    mapLoaded: boolean;
    northArrow: boolean;
    northArrowElement: TypeNorthArrow;
    overlayClickMarker?: Overlay;
    overlayNorthMarker?: Overlay;
    overviewMap: boolean;
    overviewMapHideZoom: number;
    rotation: number;
    scale: TypeScaleInfo;
    selectedFeatures: Array<TypeFeatureInfoEntry>;
    size: [number, number];
    zoom: number;
    setDefaultConfigValues: (config: TypeMapFeaturesConfig) => void;
    events: {
        onMapChangeSize: (event: ObjectEvent) => void;
        onMapMoveEnd: (event: MapEvent) => void;
        onMapPointerMove: (event: MapEvent) => void;
        onMapRotation: (event: ObjectEvent) => void;
        onMapSingleClick: (event: MapEvent) => void;
        onMapZoomEnd: (event: ObjectEvent) => void;
    };
    actions: {
        addHighlightedFeature: (feature: TypeFeatureInfoEntry) => void;
        addSelectedFeature: (feature: TypeFeatureInfoEntry) => void;
        getPixelFromCoordinate: (coord: Coordinate) => [number, number];
        hideClickMarker: () => void;
        highlightBBox: (extent: Extent) => void;
        removeHighlightedFeature: (feature: TypeFeatureInfoEntry | 'all') => void;
        removeSelectedFeature: (feature: TypeFeatureInfoEntry | 'all') => void;
        setAttribution: (attribution: string[]) => void;
        setClickCoordinates: () => void;
        setFixNorth: (ifFix: boolean) => void;
        setMapElement: (mapElem: OLMap) => void;
        setMapKeyboardPanInteractions: (panDelta: number) => void;
        setOverlayClickMarker: (overlay: Overlay) => void;
        setOverlayClickMarkerRef: (htmlRef: HTMLElement) => void;
        setOverlayNorthMarker: (overlay: Overlay) => void;
        setOverlayNorthMarkerRef: (htmlRef: HTMLElement) => void;
        setRotation: (degree: number) => void;
        setZoom: (zoom: number, duration?: number) => void;
        showClickMarker: (marker: TypeClickMarker) => void;
        transformPoints: (coords: Coordinate[], outputProjection: number) => Coordinate[];
        zoomToExtent: (extent: Extent, options?: FitOptions) => void;
        zoomToInitialExtent: () => void;
        zoomToGeoLocatorLocation: (coords: [number, number], bbox?: [number, number, number, number]) => void;
        zoomToMyLocation: (position: GeolocationPosition) => void;
    };
}
export declare function initializeMapState(set: TypeSetStore, get: TypeGetStore): IMapState;
export declare const useMapAttribution: () => string[];
export declare const useMapBasemapOptions: () => TypeBasemapOptions;
export declare const useMapCenterCoordinates: () => Coordinate;
export declare const useMapClickMarker: () => TypeClickMarker | undefined;
export declare const useMapElement: () => OLMap | undefined;
export declare const useMapExtent: () => Extent | undefined;
export declare const useMapFixNorth: () => boolean;
export declare const useMapInteraction: () => TypeInteraction;
export declare const useMapLoaded: () => boolean;
export declare const useMapNorthArrow: () => boolean;
export declare const useMapNorthArrowElement: () => TypeNorthArrow;
export declare const useMapOverviewMap: () => boolean;
export declare const useMapOverviewMapHideZoom: () => number;
export declare const useMapPointerPosition: () => TypeMapMouseInfo | undefined;
export declare const useMapProjection: () => TypeValidMapProjectionCodes;
export declare const useMapRotation: () => number;
export declare const useMapSelectedFeatures: () => TypeFeatureInfoEntry[];
export declare const useMapScale: () => TypeScaleInfo;
export declare const useMapSize: () => [number, number];
export declare const useMapZoom: () => number;
export declare const useMapStoreActions: () => {
    addHighlightedFeature: (feature: TypeFeatureInfoEntry) => void;
    addSelectedFeature: (feature: TypeFeatureInfoEntry) => void;
    getPixelFromCoordinate: (coord: Coordinate) => [number, number];
    hideClickMarker: () => void;
    highlightBBox: (extent: Extent) => void;
    removeHighlightedFeature: (feature: TypeFeatureInfoEntry | 'all') => void;
    removeSelectedFeature: (feature: TypeFeatureInfoEntry | 'all') => void;
    setAttribution: (attribution: string[]) => void;
    setClickCoordinates: () => void;
    setFixNorth: (ifFix: boolean) => void;
    setMapElement: (mapElem: OLMap) => void;
    setMapKeyboardPanInteractions: (panDelta: number) => void;
    setOverlayClickMarker: (overlay: Overlay) => void;
    setOverlayClickMarkerRef: (htmlRef: HTMLElement) => void;
    setOverlayNorthMarker: (overlay: Overlay) => void;
    setOverlayNorthMarkerRef: (htmlRef: HTMLElement) => void;
    setRotation: (degree: number) => void;
    setZoom: (zoom: number, duration?: number) => void;
    showClickMarker: (marker: TypeClickMarker) => void;
    transformPoints: (coords: Coordinate[], outputProjection: number) => Coordinate[];
    zoomToExtent: (extent: Extent, options?: FitOptions) => void;
    zoomToInitialExtent: () => void;
    zoomToGeoLocatorLocation: (coords: [number, number], bbox?: [number, number, number, number]) => void;
    zoomToMyLocation: (position: GeolocationPosition) => void;
};
export {};
